clear; clc;
hF1=figure; 
set(hF1,'Units','Normalized','Pos',[0 0.06 1 1.1],...
    'Color',[0.8 0.8 0.8]);
%Общий заголовок
uicontrol(hF1,'Style','text','Units','Normalized',...
   'Pos',[0.03 0.86 0.935 0.09],'String',...
   'ХАРАКТЕРИСТИКИ НЕЛИНЕЙНОСТИ И ХАОТИЧНОСТИ','Back',[0.8 0.8 0.8],...
   'Hor','center','FontSize',34,'FontWeight','Bold');
uicontrol(hF1,'Style','text','Units','Normalized',...
   'Position',[0.03 0.83 0.935 0.05],'String',...
   'Оценивание показателей нелинейности и хаотичности временного ряда на R скользящих окнах шириной L со сдвигом d',...
   'Back',[0.8 0.8 0.8],'Hor','center','FontSize',18,'FontWeight','Bold');
%Рамка вокруг выпадающего меню
uicontrol(hF1,'Style','Frame','Units','Norm',...
   'Pos',[0.03 0.425 0.16 0.405],'Back',[1 1 1]);
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.045 0.78 0.13 0.04],'String','Вызываемый файл',...
   'Back',[1 1 1],'Hor','center',...
   'FontWeight','Bold','FontSize',16);
%Выпадающее меню
path_my='c:\Chaos_dat\'; b=dir(path_my); str={b.name};
hmenu=uicontrol(hF1,'Style','Popupmenu','Units','Norm',...
   'Pos',[0.045 0.62 0.13 0.15],'String',str,'Hor','left');

%Заголовки и поля ввода параметров скользящего окна
uicontrol(hF1,'Style','text','Units','Norm',...
    'Back',[1 1 1]*0.8,'Fore',[0 0 0],'String','Ширина окна L',...
    'FontSize',13,'FontWeight','Bold',...
    'Pos',[0.03 0.38 0.09 0.03],'Hor','Left');
    LL=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.38 0.06 0.03],'String','200',...
   'Back',[1 1 1]*0.8,'Hor','center');
uicontrol(hF1,'Style','text','Units','Norm',...
    'Back',[1 1 1]*0.8,'Fore',[0 0 0],'String','Начало отсчёта K',...
    'FontSize',13,'FontWeight','Bold',...
    'Pos',[0.03 0.345 0.09 0.03],'Hor','Left');
    KK=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.345 0.06 0.03],'String','1',...
   'Back',[1 1 1]*0.8,'Hor','center');
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.03 0.31 0.09 0.03],'String','Сдвиг окна d',...
   'Back',[1 1 1]*0.8,'FontWeight','Bold',...
   'Hor','Left','FontSize',13);
    dd=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.31 0.06 0.03],'String','100',...
   'Back',[1 1 1]*0.8,'Hor','center');
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.03 0.275 0.09 0.03],'String','Число полос m',...
   'Back',[1 1 1]*0.8,'FontWeight','Bold','Hor','Left','FontSize',13);
  mm=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.275 0.06 0.03],'String','30',...
   'Back',[1 1 1]*0.8,'Hor','center');
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.03 0.24 0.09 0.03],'String','Отклонение D',...
   'Back',[1 1 1]*0.8,'Hor','Left','FontWeight','Bold','FontSize',13);
  DD=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.24 0.06 0.03],'String','4',...
   'Back',[1 1 1]*0.8,'Hor','center');
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.03 0.205 0.09 0.03],'String','Число окон R',...
   'Back',[1 1 1]*0.8,'Hor','Left','FontWeight','Bold','FontSize',13);
  RR=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.205 0.06 0.03],...
   'String','200','Back',[1 1 1]*0.8,'Hor','center');
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.03 0.17 0.09 0.03],'String','Дисконт alp',...
   'Back',[1 1 1]*0.8,'Hor','Left','FontWeight','Bold','FontSize',13);
  ALP=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.13 0.17 0.06 0.03],...
   'String','0.01','Back',[1 1 1]*0.8,'Hor','center');

%=====ВЫХОД======
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Выход','Back',[0.9 0.9 0.9],'FontSize',13,...
   'FontWeight','Bold','Pos',[0.03 0.02 0.1 0.04],...
   'Hor','center', 'Call','close all');

%Ввод данных и вывод графика
uicontrol(hF1,'Style','Pushbutton','Units','Norm',...
   'String','Ввод данных','Back',[0.9 0.9 0.9],'FontSize',13,...
   'FontWeight','Bold','Pos',[0.03 0.07 0.1 0.04],...
   'Hor','center','Call','H_vvod;');

%Ввод параметров
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Ввод параметров','Back',[1 1 1]*0.9,'FontSize',13,...
   'FontWeight','Bold','Pos',[0.135 0.07 0.11 0.04],'Hor',...
   'center', 'Call','H_vvod_1;');

%============РЕЗУЛЬТАТЫ АНАЛИЗА====================
%Хинич
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Тест Хинича','Back',[1 1 1]*0.9,'FontSize',13,...
   'FontWeight','Bold','Pos',[0.135 0.02 0.11 0.04],'Hor',...
   'center', 'Call','Hinich_my(Y,K,d,L,R)');
%Показатели Херста и Ляпунова
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Критерии Херста и Ляпунова','Back',[1 1 1]*0.9,'FontSize',13,...
   'Pos',[0.395 0.02 0.2 0.04],'Hor','center',...
   'FontWeight','Bold','Call','Herst_my(Y,m,K,d,D,L,R)');
%Гёльдер
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Показатель Гёльдера','Back',[1 1 1]*0.9,...
   'FontSize',13,'FontWeight','Bold',...
   'Pos',[0.395 0.07 0.15 0.04],'Hor','center',...
   'Call','Hoelder_my(Y,m,K,D,d,L,R)');

%Сегментация
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Сегментация','Back',[1 1 1]*0.9,'FontSize',13,...
   'Pos',[0.25 0.02 0.14 0.04],'FontWeight','Bold','Hor','center',...
   'Call', 'J=segment_my(Y,K,d,L,R)');
%Вариации эксцесса
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Куртозис и пик-ф-р','Back',[1 1 1]*0.9,'FontSize',13,...
   'Pos',[0.25 0.07 0.14 0.04],'FontWeight','Bold','Hor','center',...
   'Call', 'Curth_my(Y,K,d,L,R)');

%Задание номера скачка
uicontrol(hF1,'Style','text','Units','Norm',...
   'Pos',[0.55 0.06 0.15 0.04],'String','Номер скачка n',...
   'Back',[1 1 1]*0.8,'Hor','Left','FontWeight','Bold','FontSize',13);
  Nn=uicontrol(hF1,'Style','edit','Units','Norm','FontSize',13,...
   'FontWeight','Bold','Pos',[0.65 0.07 0.03 0.04],...
   'String','1','Back',[1 1 1]*0.8,'Hor','center');
%Ввод номера скачка
uicontrol(hF1,'Style','Pushbutton','Units','Norm',...
   'String','Ввод','Back',[1 1 1]*0.9,'FontSize',13,...
   'FontWeight','Bold','Pos',[0.6 0.02 0.05 0.04],'Hor',...
   'center', 'Call','H_vvod_2;');
%Вывод участков перед скачком на фазовые плоскости статистик
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','n-я бифуркация','Back',[1 1 1]*0.9,...
   'FontSize',13,'FontWeight','Bold',...
   'Pos',[0.685 0.07 0.12 0.04],'Hor','center',...
   'Call','L0=100; L1=100;[DT,H,G]=bifurk_my(Y,m,D,L0,L1,J,n);');
%Кумулятивные суммы
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Кумулятивные суммы','Back',[1 1 1]*0.9,...
   'FontSize',13,'FontWeight','Bold',...
   'Pos',[0.655 0.02 0.15 0.04],'Hor','center',...
   'Call','L0=100; L1=100;bifurk_my_1(DT,H,G,L0,L1);');
%Фрактальная размерность
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','Колебания','Back',[1 1 1]*0.9,...
   'FontSize',13,'FontWeight','Bold',...
   'Pos',[0.81 0.07 0.17 0.04],'Hor','center',...
   'Call','SSA_my(Y,K,d,L,R);');
%Персистентность
uicontrol(hF1,'Style','Push','Units','Norm',...
   'String','=========','Back',[1 1 1]*0.9,...
   'FontSize',13,'FontWeight','Bold',...
   'Pos',[0.81 0.02 0.17 0.04],'Hor','center',...
   'Call','');